// <auto-generated> Reverse-engineered 2025-11-26 09:22:52Z. Do not edit by hand. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace JobPortal.Areas.Shared.Models; // ===== admin_log.cs =====
[Table("admin_log")]
[Index("user_id", Name = "fk_adminlog_user")]
public partial class admin_log
{
    [Key]
    public int log_id { get; set; }

    public int user_id { get; set; }

    [StringLength(80)]
    public string action_type { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime timestamp { get; set; }

    [ForeignKey("user_id")]
    [InverseProperty("admin_logs")]
    public virtual user user { get; set; } = null!;
}

 // ===== ai_parsed_resume.cs =====
[Index("job_listing_id", Name = "idx_ai_parsed_resumes_job")]
[Index("user_id", Name = "idx_ai_parsed_resumes_user")]
[Index("resume_id", "job_listing_id", Name = "ux_ai_parsed_resumes_latest", IsUnique = true)]
[MySqlCollation("utf8mb4_0900_ai_ci")]
public partial class ai_parsed_resume
{
    [Key]
    public int parsed_id { get; set; }

    public int resume_id { get; set; }

    public int user_id { get; set; }

    public int? job_listing_id { get; set; }

    public string parsed_json { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime updated_at { get; set; }

    [ForeignKey("job_listing_id")]
    [InverseProperty("ai_parsed_resumes")]
    public virtual job_listing? job_listing { get; set; }

    [ForeignKey("resume_id")]
    [InverseProperty("ai_parsed_resumes")]
    public virtual resume resume { get; set; } = null!;

    [ForeignKey("user_id")]
    [InverseProperty("ai_parsed_resumes")]
    public virtual user user { get; set; } = null!;
}

 // ===== ai_rank_override.cs =====
[Index("application_id", Name = "idx_ai_overrides_app")]
[Index("job_listing_id", Name = "idx_ai_overrides_job")]
[Index("user_id", Name = "idx_ai_overrides_user")]
[MySqlCollation("utf8mb4_0900_ai_ci")]
public partial class ai_rank_override
{
    [Key]
    public int override_id { get; set; }

    public int application_id { get; set; }

    public int job_listing_id { get; set; }

    public int user_id { get; set; }

    public sbyte direction { get; set; }

    [StringLength(300)]
    public string reason { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime created_at { get; set; }

    [ForeignKey("job_listing_id")]
    [InverseProperty("ai_rank_overrides")]
    public virtual job_listing job_listing { get; set; } = null!;

    [ForeignKey("user_id")]
    [InverseProperty("ai_rank_overrides")]
    public virtual user user { get; set; } = null!;
}

 // ===== ai_resume_evaluation.cs =====
[Table("ai_resume_evaluation")]
[Index("job_listing_id", Name = "fk_eval_job")]
[Index("resume_id", Name = "fk_eval_resume")]
[Index("date_evaluated", Name = "idx_ai_eval_date")]
public partial class ai_resume_evaluation
{
    [Key]
    public int evaluation_id { get; set; }

    public int job_listing_id { get; set; }

    public int resume_id { get; set; }

    public byte? match_score { get; set; }

    [Column(TypeName = "json")]
    public string? breakdown_json { get; set; }

    [StringLength(500)]
    public string? explanation { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime date_evaluated { get; set; }

    [ForeignKey("job_listing_id")]
    [InverseProperty("ai_resume_evaluations")]
    public virtual job_listing job_listing { get; set; } = null!;

    [ForeignKey("resume_id")]
    [InverseProperty("ai_resume_evaluations")]
    public virtual resume resume { get; set; } = null!;
}

 // ===== ai_scoring_rule.cs =====
[Index("job_listing_id", Name = "fk_rules_job")]
[Index("user_id", "job_listing_id", Name = "ux_ai_scoring_rules_owner_job", IsUnique = true)]
[MySqlCollation("utf8mb4_0900_ai_ci")]
public partial class ai_scoring_rule
{
    [Key]
    public int rule_id { get; set; }

    public int user_id { get; set; }

    public int job_listing_id { get; set; }

    [Column(TypeName = "json")]
    public string rule_json { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime updated_at { get; set; }

    [ForeignKey("job_listing_id")]
    [InverseProperty("ai_scoring_rules")]
    public virtual job_listing job_listing { get; set; } = null!;

    [ForeignKey("user_id")]
    [InverseProperty("ai_scoring_rules")]
    public virtual user user { get; set; } = null!;
}

 // ===== company.cs =====
[Table("company")]
[Index("user_id", Name = "UX_company_user", IsUnique = true)]
[Index("company_name", Name = "idx_company_name")]
public partial class company
{
    [Key]
    public int company_id { get; set; }

    public int user_id { get; set; }

    [StringLength(160)]
    public string company_name { get; set; } = null!;

    [StringLength(120)]
    public string? company_industry { get; set; }

    [StringLength(120)]
    public string? company_location { get; set; }

    [Column(TypeName = "text")]
    public string? company_description { get; set; }

    [StringLength(255)]
    public string? company_photo { get; set; }

    [StringLength(20)]
    public string? company_status { get; set; }

    [InverseProperty("company")]
    public virtual ICollection<job_listing> job_listings { get; set; } = new List<job_listing>();

    [ForeignKey("user_id")]
    [InverseProperty("company")]
    public virtual user user { get; set; } = null!;
}

 // ===== conversation.cs =====
[Table("conversation")]
[Index("flagged_by_user_id", Name = "fk_conv_flagged_by_user")]
[Index("job_listing_id", Name = "fk_conversation_job")]
[Index("last_message_at", Name = "idx_conv_last_at")]
[Index("last_message_at", "is_blocked", Name = "idx_conv_last_blocked")]
[Index("recruiter_id", "last_message_at", Name = "idx_conv_recruiter")]
public partial class conversation
{
    [Key]
    public int conversation_id { get; set; }

    public int job_listing_id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime created_at { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? last_message_at { get; set; }

    [StringLength(200)]
    public string? last_snippet { get; set; }

    public int unread_for_recruiter { get; set; }

    public int unread_for_candidate { get; set; }

    public int? recruiter_id { get; set; }

    public int? candidate_id { get; set; }

    [StringLength(200)]
    public string? job_title { get; set; }

    [StringLength(200)]
    public string? candidate_name { get; set; }

    public bool is_blocked { get; set; }

    [StringLength(255)]
    public string? blocked_reason { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? flagged_at { get; set; }

    public int? flagged_by_user_id { get; set; }

    [InverseProperty("conversation")]
    public virtual ICollection<conversation_monitor> conversation_monitors { get; set; } = new List<conversation_monitor>();

    [ForeignKey("flagged_by_user_id")]
    [InverseProperty("conversations")]
    public virtual user? flagged_by_user { get; set; }

    [ForeignKey("job_listing_id")]
    [InverseProperty("conversations")]
    public virtual job_listing job_listing { get; set; } = null!;

    [InverseProperty("conversation")]
    public virtual ICollection<message> messages { get; set; } = new List<message>();
}

 // ===== conversation_monitor.cs =====
[Table("conversation_monitor")]
[Index("conversation_id", Name = "fk_monitor_conv")]
[Index("flagged_by_user_id", Name = "fk_monitor_flagged_by_user")]
[Index("user_id", Name = "fk_monitor_user")]
public partial class conversation_monitor
{
    [Key]
    public int monitor_id { get; set; }

    public int conversation_id { get; set; }

    public int user_id { get; set; }

    public bool flag { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? date_reviewed { get; set; }

    [Column(TypeName = "text")]
    public string? flag_reason { get; set; }

    public int? flagged_by_user_id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? flagged_at { get; set; }

    [ForeignKey("conversation_id")]
    [InverseProperty("conversation_monitors")]
    public virtual conversation conversation { get; set; } = null!;

    [ForeignKey("flagged_by_user_id")]
    [InverseProperty("conversation_monitorflagged_by_users")]
    public virtual user? flagged_by_user { get; set; }

    [ForeignKey("user_id")]
    [InverseProperty("conversation_monitorusers")]
    public virtual user user { get; set; } = null!;
}

 // ===== email_verification.cs =====
[Table("email_verification")]
[Index("email", "purpose", Name = "idx_email_purpose")]
[Index("expires_at", "used", Name = "idx_exp_used")]
[Index("email", "token", Name = "uq_email_latest", IsUnique = true)]
public partial class email_verification
{
    [Key]
    public int token_id { get; set; }

    [StringLength(190)]
    public string email { get; set; } = null!;

    public Guid token { get; set; }

    [Column(TypeName = "enum('RecruiterRegister','SeekerRegister','PasswordReset')")]
    public string purpose { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime expires_at { get; set; }

    public bool used { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime created_at { get; set; }
}

 // ===== job_application.cs =====
[Table("job_application")]
[Index("job_listing_id", "application_status", Name = "ix_app_job_status")]
[Index("job_listing_id", Name = "ix_application_job")]
[Index("user_id", Name = "ix_application_user")]
public partial class job_application
{
    [Key]
    public int application_id { get; set; }

    public int user_id { get; set; }

    public int job_listing_id { get; set; }

    [Column(TypeName = "enum('Submitted','AI-Screened','Shortlisted','Interview','Offer','Hired','Rejected')")]
    public string application_status { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime date_updated { get; set; }

    [StringLength(255)]
    [MySqlCharSet("utf8mb3")]
    [MySqlCollation("utf8mb3_general_ci")]
    public string? resume_path { get; set; }

    public int? expected_salary { get; set; }

    [StringLength(255)]
    [MySqlCharSet("utf8mb3")]
    [MySqlCollation("utf8mb3_general_ci")]
    public string? description { get; set; }

    [ForeignKey("job_listing_id")]
    [InverseProperty("job_applications")]
    public virtual job_listing job_listing { get; set; } = null!;

    [InverseProperty("application")]
    public virtual ICollection<job_offer> job_offers { get; set; } = new List<job_offer>();

    [InverseProperty("application")]
    public virtual ICollection<job_seeker_note> job_seeker_notes { get; set; } = new List<job_seeker_note>();

    [ForeignKey("user_id")]
    [InverseProperty("job_applications")]
    public virtual user user { get; set; } = null!;
}

 // ===== job_favourite.cs =====
[Index("job_listing_id", Name = "job_listing_id")]
[Index("user_id", "job_listing_id", Name = "user_id", IsUnique = true)]
public partial class job_favourite
{
    [Key]
    public int fav_id { get; set; }

    public int user_id { get; set; }

    public int job_listing_id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? created_at { get; set; }

    [ForeignKey("job_listing_id")]
    [InverseProperty("job_favourites")]
    public virtual job_listing job_listing { get; set; } = null!;

    [ForeignKey("user_id")]
    [InverseProperty("job_favourites")]
    public virtual user user { get; set; } = null!;
}

 // ===== job_listing.cs =====
[Table("job_listing")]
[Index("company_id", Name = "ix_joblisting_company")]
[Index("user_id", Name = "ix_joblisting_user")]
public partial class job_listing
{
    [Key]
    public int job_listing_id { get; set; }

    public int user_id { get; set; }

    public int company_id { get; set; }

    [StringLength(160)]
    public string job_title { get; set; } = null!;

    [Column(TypeName = "text")]
    public string? job_description { get; set; }

    [Column(TypeName = "text")]
    public string? job_requirements { get; set; }

    [Column(TypeName = "text")]
    public string? job_requirements_nice { get; set; }

    [Precision(10, 2)]
    public decimal? salary_min { get; set; }

    [Precision(10, 2)]
    public decimal? salary_max { get; set; }

    [Column(TypeName = "enum('Draft','Open','Paused','Closed')")]
    public string job_status { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime date_posted { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? expiry_date { get; set; }

    [StringLength(50)]
    [MySqlCharSet("utf8mb3")]
    [MySqlCollation("utf8mb3_general_ci")]
    public string job_type { get; set; } = null!;

    [StringLength(50)]
    [MySqlCharSet("utf8mb3")]
    [MySqlCollation("utf8mb3_general_ci")]
    public string work_mode { get; set; } = null!;

    [StringLength(50)]
    public string job_category { get; set; } = null!;

    [InverseProperty("job_listing")]
    public virtual ICollection<ai_parsed_resume> ai_parsed_resumes { get; set; } = new List<ai_parsed_resume>();

    [InverseProperty("job_listing")]
    public virtual ICollection<ai_rank_override> ai_rank_overrides { get; set; } = new List<ai_rank_override>();

    [InverseProperty("job_listing")]
    public virtual ICollection<ai_resume_evaluation> ai_resume_evaluations { get; set; } = new List<ai_resume_evaluation>();

    [InverseProperty("job_listing")]
    public virtual ICollection<ai_scoring_rule> ai_scoring_rules { get; set; } = new List<ai_scoring_rule>();

    [ForeignKey("company_id")]
    [InverseProperty("job_listings")]
    public virtual company company { get; set; } = null!;

    [InverseProperty("job_listing")]
    public virtual ICollection<conversation> conversations { get; set; } = new List<conversation>();

    [InverseProperty("job_listing")]
    public virtual ICollection<job_application> job_applications { get; set; } = new List<job_application>();

    [InverseProperty("job_listing")]
    public virtual ICollection<job_favourite> job_favourites { get; set; } = new List<job_favourite>();

    [InverseProperty("job_listing")]
    public virtual ICollection<job_post_approval> job_post_approvals { get; set; } = new List<job_post_approval>();

    [ForeignKey("user_id")]
    [InverseProperty("job_listings")]
    public virtual user user { get; set; } = null!;
}

 // ===== job_offer.cs =====
[Table("job_offer")]
[Index("application_id", Name = "ix_offer_app")]
[Index("offer_status", Name = "ix_offer_status")]
[Index("candidate_token", Name = "uq_offer_token", IsUnique = true)]
public partial class job_offer
{
    [Key]
    public int offer_id { get; set; }

    public int application_id { get; set; }

    [Column(TypeName = "enum('Draft','Sent','Accepted','Declined','Withdrawn','Expired')")]
    public string? offer_status { get; set; }

    [Precision(12, 2)]
    public decimal? salary_offer { get; set; }

    public DateOnly? start_date { get; set; }

    [StringLength(60)]
    public string? contract_type { get; set; }

    [Column(TypeName = "text")]
    public string? notes { get; set; }

    public Guid candidate_token { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? date_sent { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime date_updated { get; set; }

    [ForeignKey("application_id")]
    [InverseProperty("job_offers")]
    public virtual job_application application { get; set; } = null!;
}

 // ===== job_post_approval.cs =====
[Table("job_post_approval")]
[Index("user_id", Name = "fk_approval_admin")]
[Index("job_listing_id", Name = "fk_approval_job")]
public partial class job_post_approval
{
    [Key]
    public int approval_id { get; set; }

    public int user_id { get; set; }

    public int job_listing_id { get; set; }

    [Column(TypeName = "enum('Pending','Approved','ChangesRequested','Rejected')")]
    public string approval_status { get; set; } = null!;

    [Column(TypeName = "text")]
    public string? comments { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? date_approved { get; set; }

    [ForeignKey("job_listing_id")]
    [InverseProperty("job_post_approvals")]
    public virtual job_listing job_listing { get; set; } = null!;

    [ForeignKey("user_id")]
    [InverseProperty("job_post_approvals")]
    public virtual user user { get; set; } = null!;
}

 // ===== job_seeker_note.cs =====
[Table("job_seeker_note")]
[Index("application_id", Name = "fk_note_app")]
[Index("job_recruiter_id", Name = "fk_note_recruiter")]
[Index("job_seeker_id", Name = "fk_note_seeker")]
public partial class job_seeker_note
{
    [Key]
    public int note_id { get; set; }

    public int job_seeker_id { get; set; }

    public int job_recruiter_id { get; set; }

    public int application_id { get; set; }

    [Column(TypeName = "text")]
    public string note_text { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime created_at { get; set; }

    [ForeignKey("application_id")]
    [InverseProperty("job_seeker_notes")]
    public virtual job_application application { get; set; } = null!;

    [ForeignKey("job_recruiter_id")]
    [InverseProperty("job_seeker_notejob_recruiters")]
    public virtual user job_recruiter { get; set; } = null!;

    [ForeignKey("job_seeker_id")]
    [InverseProperty("job_seeker_notejob_seekers")]
    public virtual user job_seeker { get; set; } = null!;
}

 // ===== message.cs =====
[Table("message")]
[Index("conversation_id", "msg_timestamp", Name = "idx_msg_conv_ts")]
[Index("receiver_id", "is_read", "msg_timestamp", Name = "idx_msg_recv_unread_ts")]
[Index("sender_id", "msg_timestamp", Name = "idx_msg_sender_ts")]
[Index("conversation_id", Name = "ix_message_conv")]
[Index("receiver_id", Name = "ix_message_receiver")]
public partial class message
{
    [Key]
    public int message_id { get; set; }

    public int conversation_id { get; set; }

    public int sender_id { get; set; }

    public int receiver_id { get; set; }

    [Column(TypeName = "text")]
    public string msg_content { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime msg_timestamp { get; set; }

    public bool is_read { get; set; }

    [ForeignKey("conversation_id")]
    [InverseProperty("messages")]
    public virtual conversation conversation { get; set; } = null!;

    [ForeignKey("receiver_id")]
    [InverseProperty("messagereceivers")]
    public virtual user receiver { get; set; } = null!;

    [ForeignKey("sender_id")]
    [InverseProperty("messagesenders")]
    public virtual user sender { get; set; } = null!;
}

 // ===== notification.cs =====
[Table("notification")]
[Index("user_id", Name = "ix_notification_user")]
public partial class notification
{
    [Key]
    public int notification_id { get; set; }

    public int user_id { get; set; }

    [StringLength(160)]
    public string notification_title { get; set; } = null!;

    [Column(TypeName = "text")]
    public string notification_msg { get; set; } = null!;

    [StringLength(50)]
    public string? notification_type { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime notification_date_created { get; set; }

    public bool notification_read_status { get; set; }

    [ForeignKey("user_id")]
    [InverseProperty("notifications")]
    public virtual user user { get; set; } = null!;
}

 // ===== notification_preference.cs =====
[Table("notification_preference")]
[Index("user_id", Name = "fk_pref_user")]
public partial class notification_preference
{
    [Key]
    public int preference_id { get; set; }

    public int user_id { get; set; }

    public bool allow_email { get; set; }

    public bool allow_inApp { get; set; }

    public bool notif_job_updates { get; set; }

    public bool notif_messages { get; set; }

    public bool notif_reminders { get; set; }

    [ForeignKey("user_id")]
    [InverseProperty("notification_preferences")]
    public virtual user user { get; set; } = null!;
}

 // ===== resume.cs =====
[Table("resume")]
[Index("user_id", Name = "ix_resume_user")]
public partial class resume
{
    [Key]
    public int resume_id { get; set; }

    public int user_id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime upload_date { get; set; }

    [StringLength(255)]
    public string file_path { get; set; } = null!;

    [InverseProperty("resume")]
    public virtual ICollection<ai_parsed_resume> ai_parsed_resumes { get; set; } = new List<ai_parsed_resume>();

    [InverseProperty("resume")]
    public virtual ICollection<ai_resume_evaluation> ai_resume_evaluations { get; set; } = new List<ai_resume_evaluation>();

    [InverseProperty("resume")]
    public virtual ICollection<resume_feedback_history> resume_feedback_histories { get; set; } = new List<resume_feedback_history>();

    [ForeignKey("user_id")]
    [InverseProperty("resumes")]
    public virtual user user { get; set; } = null!;
}

 // ===== resume_feedback_history.cs =====
[Table("resume_feedback_history")]
[Index("resume_id", Name = "ix_feedback_resume")]
[Index("user_id", Name = "ix_feedback_user")]
public partial class resume_feedback_history
{
    [Key]
    public int feedback_id { get; set; }

    public int resume_id { get; set; }

    public int user_id { get; set; }

    [Column(TypeName = "text")]
    public string feedback_text { get; set; } = null!;

    [Precision(5, 2)]
    public decimal? score { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime created_at { get; set; }

    [ForeignKey("resume_id")]
    [InverseProperty("resume_feedback_histories")]
    public virtual resume resume { get; set; } = null!;

    [ForeignKey("user_id")]
    [InverseProperty("resume_feedback_histories")]
    public virtual user user { get; set; } = null!;
}

 // ===== template.cs =====
[Table("template")]
[Index("user_id", Name = "fk_template_user")]
public partial class template
{
    [Key]
    public int template_id { get; set; }

    public int user_id { get; set; }

    [StringLength(120)]
    public string template_name { get; set; } = null!;

    [StringLength(160)]
    public string? template_subject { get; set; }

    [Column(TypeName = "text")]
    public string template_body { get; set; } = null!;

    [Column(TypeName = "enum('Active','Archived')")]
    public string template_status { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime date_created { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime date_updated { get; set; }

    [ForeignKey("user_id")]
    [InverseProperty("templates")]
    public virtual user user { get; set; } = null!;
}

 // ===== user.cs =====
[Table("user")]
[Index("email", Name = "email", IsUnique = true)]
public partial class user
{
    [Key]
    public int user_id { get; set; }

    [StringLength(60)]
    public string first_name { get; set; } = null!;

    [StringLength(60)]
    public string last_name { get; set; } = null!;

    [StringLength(190)]
    public string email { get; set; } = null!;

    [StringLength(255)]
    public string password_hash { get; set; } = null!;

    [Column(TypeName = "enum('Admin','Recruiter','JobSeeker')")]
    public string user_role { get; set; } = null!;

    public bool user_2FA { get; set; }

    [StringLength(100)]
    public string? user_2FA_secret { get; set; }

    [Column(TypeName = "enum('Active','Suspended','Inactive','Unverified')")]
    public string user_status { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime created_at { get; set; }

    [StringLength(30)]
    public string? phone { get; set; }

    [Column(TypeName = "text")]
    public string? address { get; set; }

    [Column(TypeName = "text")]
    public string? work_experience { get; set; }

    [Column(TypeName = "text")]
    public string? education { get; set; }

    [Column(TypeName = "text")]
    public string? skills { get; set; }

    [StringLength(100)]
    public string? target_industry { get; set; }

    [StringLength(255)]
    public string? profile_picture { get; set; }

    [InverseProperty("user")]
    public virtual ICollection<admin_log> admin_logs { get; set; } = new List<admin_log>();

    [InverseProperty("user")]
    public virtual ICollection<ai_parsed_resume> ai_parsed_resumes { get; set; } = new List<ai_parsed_resume>();

    [InverseProperty("user")]
    public virtual ICollection<ai_rank_override> ai_rank_overrides { get; set; } = new List<ai_rank_override>();

    [InverseProperty("user")]
    public virtual ICollection<ai_scoring_rule> ai_scoring_rules { get; set; } = new List<ai_scoring_rule>();

    [InverseProperty("user")]
    public virtual company? company { get; set; }

    [InverseProperty("flagged_by_user")]
    public virtual ICollection<conversation_monitor> conversation_monitorflagged_by_users { get; set; } = new List<conversation_monitor>();

    [InverseProperty("user")]
    public virtual ICollection<conversation_monitor> conversation_monitorusers { get; set; } = new List<conversation_monitor>();

    [InverseProperty("flagged_by_user")]
    public virtual ICollection<conversation> conversations { get; set; } = new List<conversation>();

    [InverseProperty("user")]
    public virtual ICollection<job_application> job_applications { get; set; } = new List<job_application>();

    [InverseProperty("user")]
    public virtual ICollection<job_favourite> job_favourites { get; set; } = new List<job_favourite>();

    [InverseProperty("user")]
    public virtual ICollection<job_listing> job_listings { get; set; } = new List<job_listing>();

    [InverseProperty("user")]
    public virtual ICollection<job_post_approval> job_post_approvals { get; set; } = new List<job_post_approval>();

    [InverseProperty("job_recruiter")]
    public virtual ICollection<job_seeker_note> job_seeker_notejob_recruiters { get; set; } = new List<job_seeker_note>();

    [InverseProperty("job_seeker")]
    public virtual ICollection<job_seeker_note> job_seeker_notejob_seekers { get; set; } = new List<job_seeker_note>();

    [InverseProperty("receiver")]
    public virtual ICollection<message> messagereceivers { get; set; } = new List<message>();

    [InverseProperty("sender")]
    public virtual ICollection<message> messagesenders { get; set; } = new List<message>();

    [InverseProperty("user")]
    public virtual ICollection<notification_preference> notification_preferences { get; set; } = new List<notification_preference>();

    [InverseProperty("user")]
    public virtual ICollection<notification> notifications { get; set; } = new List<notification>();

    [InverseProperty("user")]
    public virtual ICollection<resume_feedback_history> resume_feedback_histories { get; set; } = new List<resume_feedback_history>();

    [InverseProperty("user")]
    public virtual ICollection<resume> resumes { get; set; } = new List<resume>();

    [InverseProperty("user")]
    public virtual ICollection<template> templates { get; set; } = new List<template>();
}

